var cityData3 = [

 {
    value: '130000',
    text: '成都市',
    children: [{
        value: "130100",
        text: "锦江区",
        children: [{
            value: "130102",
            text: "督院街街道"
        }, {
            value: "130103",
            text: "盐市口街道"
        }, {
            value: "130104",
            text: "春熙路街道"
        }, {
            value: "130105",
            text: "书院街街道"
        }, {
            value: "130107",
            text: "合江亭街道"
        }, {
            value: "130108",
            text: "水井坊街道"
        }, {
            value: "130121",
            text: "牛市口街道"
        }, {
            value: "130123",
            text: "龙舟路街道"
        }, {
            value: "130124",
            text: "双桂路街道"
        }, {
            value: "130125",
            text: "莲新街道"
        }, {
            value: "130126",
            text: "沙河街道"
        }, {
            value: "130127",
            text: "东光街道"
        }, {
            value: "130128",
            text: "狮子山街道"
        }, {
            value: "130129",
            text: "成龙路街道"
        }, {
            value: "130130",
            text: "柳江街道"
        }, {
            value: "130131",
            text: "三圣街道"
        }]
    }, {
        value: "130200",
        text: "青羊区",
        children: [{
            value: "130202",
            text: "太升路街道"
        }, {
            value: "130203",
            text: "草市街街道"
        }, {
            value: "130204",
            text: "西御河街道"
        }, {
            value: "130205",
            text: "汪家拐街道"
        }, {
            value: "130207",
            text: "少城街道"
        }, {
            value: "130208",
            text: "新华西路街道"
        }, {
            value: "130223",
            text: "草堂街道"
        }, {
            value: "130224",
            text: "府南街道"
        }, {
            value: "130225",
            text: "光华街道"
        }, {
            value: "130227",
            text: "东坡街道"
        }, {
            value: "130229",
            text: "金沙街道"
        }, {
            value: "130230",
            text: "黄田坝街道"
        }, {
            value: "130281",
            text: "苏坡街道"
        }, {
            value: "130283",
            text: "文家街道"
        }]
    }, {
        value: "130300",
        text: "金牛区",
        children: [{
            value: "130302",
            text: "西安路街道"
        }, {
            value: "130303",
            text: "西华街道"
        }, {
            value: "130304",
            text: "人民北路街道"
        }, {
            value: "130321",
            text: "荷花池街道"
        }, {
            value: "130322",
            text: "驷马桥街道"
        }, {
            value: "130323",
            text: "茶店子街道"
        }, {
            value: "130324",
            text: "抚琴街道"
        }, {
            value: "130398",
            text: "九里堤街道"
        }, {
            value: "130399",
            text: "五块石街道"
        }, {
            value: "130321",
            text: "荷花池街道"
        }, {
            value: "130322",
            text: "黄忠街道"
        }, {
            value: "130323",
            text: "营门口街道"
        }, {
            value: "130324",
            text: "金泉街道"
        }, {
            value: "130398",
            text: "沙河源街道"
        }, {
            value: "130399",
            text: "天回镇街道"
        }, {
            value: "130399",
            text: "凤凰山街道"
        }]
    }, {
        value: "130400",
        text: "武侯区",
        children: [{
            value: "130402",
            text: "浆洗街街道"
        }, {
            value: "130403",
            text: "望江路街道"
        }, {
            value: "130404",
            text: "玉林街道"
        }, {
            value: "130406",
            text: "跳伞塔街道"
        }, {
            value: "130421",
            text: "火车南站街道"
        }, {
            value: "130423",
            text: "双楠街道"
        }, {
            value: "130424",
            text: "晋阳街道"
        }, {
            value: "130425",
            text: "红牌楼街道"
        }, {
            value: "130426",
            text: "簇桥街道"
        }, {
            value: "130427",
            text: "机投桥街道"
        }, {
            value: "130428",
            text: "金花桥街道"
        }, {
            value: "130429",
            text: "簇锦街道"
        }, {
            value: "130430",
            text: "华兴街道"
        }, {
            value: "130431",
            text: "芳草街道"
        }, {
            value: "130432",
            text: "肖家河街道"
        }, {
            value: "130433",
            text: "石羊场街道"
        }, {
            value: "130434",
            text: "桂溪街道"
        }]
    }, {
        value: "130500",
        text: "成华区",
        children: [{
            value: "130502",
            text: "猛追湾街道"
        }, {
            value: "130503",
            text: "双桥子街道"
        }, {
            value: "130521",
            text: "建设路街道"
        }, {
            value: "130522",
            text: "府青路街道"
        }, {
            value: "130523",
            text: "二仙桥街道"
        }, {
            value: "130524",
            text: "跳蹬河街道"
        }, {
            value: "130525",
            text: "双水碾街道"
        }, {
            value: "130526",
            text: "万年场街道"
        }, {
            value: "130527",
            text: "桃蹊路街道"
        }, {
            value: "130528",
            text: "圣灯街道"
        }, {
            value: "130529",
            text: "保和街道"
        }, {
            value: "130530",
            text: "青龙街道"
        }, {
            value: "130531",
            text: "龙潭街道"
        }, {
            value: "130532",
            text: "白莲池街道"
        }]
    }, {
        value: "130600",
        text: "龙泉驿区",
        children: [{
            value: "130602",
            text: "龙泉街道"
        }, {
            value: "130603",
            text: "大面街道"
        }, {
            value: "130604",
            text: "十陵街道"
        }, {
            value: "130621",
            text: "同安街道"
        }, {
            value: "130622",
            text: "洛带镇"
        }, {
            value: "130623",
            text: "西河镇"
        }, {
            value: "130624",
            text: "洪安镇"
        }, {
            value: "130625",
            text: "柏合镇"
        }, {
            value: "130626",
            text: "茶店镇"
        }, {
            value: "130627",
            text: "黄土镇"
        }, {
            value: "130628",
            text: "山泉镇"
        }, {
            value: "130629",
            text: "万兴乡"
        }]
    }, {
        value: "130700",
        text: "青白江区",
        children: [{
            value: "130702",
            text: "红阳街道"
        }, {
            value: "130703",
            text: "大弯街道"
        }, {
            value: "130705",
            text: "弥牟镇"
        }, {
            value: "130706",
            text: "大同镇"
        }, {
            value: "130721",
            text: "城厢镇"
        }, {
            value: "130722",
            text: "祥福镇"
        }, {
            value: "130723",
            text: "姚渡镇"
        }, {
            value: "130724",
            text: "清泉镇"
        }, {
            value: "130725",
            text: "龙王镇"
        }, {
            value: "130726",
            text: "福洪镇"
        }, {
            value: "130727",
            text: "人和乡"
        }]
    }, {
        value: "130800",
        text: "新都区",
        children: [{
            value: "130802",
            text: "大丰街道"
        }, {
            value: "130803",
            text: "三河街道"
        }, {
            value: "130804",
            text: "新都街道"
        }, {
            value: "130821",
            text: "石板滩镇"
        }, {
            value: "130822",
            text: "新繁镇"
        }, {
            value: "130823",
            text: "新民镇"
        }, {
            value: "130824",
            text: "泰兴镇"
        }, {
            value: "130825",
            text: "斑竹园镇"
        }, {
            value: "130826",
            text: "清流镇"
        }, {
            value: "130827",
            text: "马家镇"
        }, {
            value: "130828",
            text: "龙桥镇"
        }, {
            value: "130829",
            text: "木兰镇"
        }, {
            value: "130829",
            text: "军屯镇"
        }]
    }, {
        value: "130900",
        text: "温江区",
        children: [{
            value: "130902",
            text: "柳城街道"
        }, {
            value: "130903",
            text: "公平街道"
        }, {
            value: "130921",
            text: "涌泉街道"
        }, {
            value: "130922",
            text: "天府街道"
        }, {
            value: "130923",
            text: "和盛镇"
        }, {
            value: "130924",
            text: "永盛镇"
        }, {
            value: "130925",
            text: "金马镇"
        }, {
            value: "130926",
            text: "永宁镇"
        }, {
            value: "130927",
            text: "万春镇"
        }, {
            value: "130928",
            text: "寿安镇"
        }]
    }, {
        value: "131000",
        text: "双流区",
        children: [{
            value: "131002",
            text: "东升街道"
        }, {
            value: "131003",
            text: "西航港街道"
        }, {
            value: "131022",
            text: "华阳镇街道"
        }, {
            value: "131023",
            text: "中和街道"
        }, {
            value: "131024",
            text: "九江街道"
        }, {
            value: "131025",
            text: "黄甲街道"
        }, {
            value: "131026",
            text: "公兴街道"
        }, {
            value: "131028",
            text: "协和街道"
        }, {
            value: "131051",
            text: "太平镇"
        }, {
            value: "131052",
            text: "永兴镇"
        }, {
            value: "131081",
            text: "籍田镇"
        }, {
            value: "131082",
            text: "正兴镇"
        }, {
            value: "131083",
            text: "彭镇"
        }, {
            value: "131083",
            text: "大林镇"
        }, {
            value: "131083",
            text: "煎茶镇"
        }, {
            value: "131083",
            text: "黄龙溪镇"
        }, {
            value: "131083",
            text: "永安镇"
        }, {
            value: "131083",
            text: "黄水镇"
        }, {
            value: "131083",
            text: "金桥镇"
        }, {
            value: "131083",
            text: "胜利镇"
        }, {
            value: "131083",
            text: "新兴镇"
        }, {
            value: "131083",
            text: "兴隆镇"
        }, {
            value: "131083",
            text: "万安镇"
        }, {
            value: "131083",
            text: "白沙镇"
        }, {
            value: "131083",
            text: "三星镇"
        }, {
            value: "131083",
            text: "合江镇"
        }]
    }, {
        value: "131100",
        text: "金堂县",
        children: [{
            value: "131102",
            text: "赵镇街道"
        }, {
            value: "131121",
            text: "三星镇"
        }, {
            value: "131122",
            text: "清江镇"
        }, {
            value: "131123",
            text: "官仓镇"
        }, {
            value: "131124",
            text: "淮口镇"
        }, {
            value: "131125",
            text: "白果镇"
        }, {
            value: "131126",
            text: "五凤镇"
        }, {
            value: "131127",
            text: "高板镇"
        }, {
            value: "131128",
            text: "三溪镇"
        }, {
            value: "131181",
            text: "福兴镇"
        }, {
            value: "131182",
            text: "金龙镇"
        }, {
            value: "131183",
            text: "赵家镇"
        }, {
            value: "131183",
            text: "竹篙镇"
        }, {
            value: "131183",
            text: "广兴镇"
        }, {
            value: "131183",
            text: "隆盛镇"
        }, {
            value: "131183",
            text: "转龙镇"
        }, {
            value: "131183",
            text: "土桥镇"
        }, {
            value: "131183",
            text: "云合镇"
        }, {
            value: "131183",
            text: "又新镇"
        }, {
            value: "131183",
            text: "栖贤乡"
        }, {
            value: "131183",
            text: "平桥乡"
        }]
    }, {
        value: "131100",
        text: "郫县",
        children: [{
            value: "131102",
            text: "郫筒街道"
        }, {
            value: "131121",
            text: "合作街道"
        }, {
            value: "131122",
            text: "西园街道"
        }, {
            value: "131123",
            text: "团结镇"
        }, {
            value: "131124",
            text: "犀浦镇"
        }, {
            value: "131125",
            text: "花园镇"
        }, {
            value: "131126",
            text: "唐昌镇"
        }, {
            value: "131127",
            text: "安德镇"
        }, {
            value: "131128",
            text: "三道堰镇"
        }, {
            value: "131181",
            text: "安靖镇"
        }, {
            value: "131182",
            text: "红光镇"
        }, {
            value: "131183",
            text: "新民场镇"
        }, {
            value: "131183",
            text: "德源镇"
        }, {
            value: "131183",
            text: "友爱镇"
        }, {
            value: "131183",
            text: "古城镇"
        }, {
            value: "131183",
            text: "唐元镇"
        }]
    }, {
        value: "131100",
        text: "大邑县",
        children: [{
            value: "131102",
            text: "晋原镇街道"
        }, {
            value: "131121",
            text: "王泗镇"
        }, {
            value: "131122",
            text: "新场镇"
        }, {
            value: "131123",
            text: "悦来镇"
        }, {
            value: "131124",
            text: "安仁镇"
        }, {
            value: "131125",
            text: "出江镇"
        }, {
            value: "131126",
            text: "花水湾镇"
        }, {
            value: "131127",
            text: "西岭镇"
        }, {
            value: "131128",
            text: "斜源镇"
        }, {
            value: "131181",
            text: "董场镇"
        }, {
            value: "131182",
            text: "韩场镇"
        }, {
            value: "131183",
            text: "三岔镇"
        }, {
            value: "131183",
            text: "上安镇"
        }, {
            value: "131183",
            text: "苏家镇"
        }, {
            value: "131183",
            text: "青霞镇"
        }, {
            value: "131183",
            text: "沙渠镇"
        }, {
            value: "131183",
            text: "蔡场镇"
        }, {
            value: "131183",
            text: "雾山乡"
        }, {
            value: "131183",
            text: "金星乡"
        }, {
            value: "131183",
            text: "鹤鸣乡"
        }]
    }, {
        value: "131100",
        text: "蒲江县",
        children: [{
            value: "131102",
            text: "鹤山街道"
        }, {
            value: "131121",
            text: "大塘镇"
        }, {
            value: "131122",
            text: "寿安镇"
        }, {
            value: "131123",
            text: "朝阳湖镇"
        }, {
            value: "131124",
            text: "西来镇"
        }, {
            value: "131125",
            text: "大兴镇"
        }, {
            value: "131126",
            text: "甘溪镇"
        }, {
            value: "131127",
            text: "成佳镇"
        }, {
            value: "131128",
            text: "复兴乡"
        }, {
            value: "131181",
            text: "光明乡"
        }, {
            value: "131182",
            text: "白云乡"
        }, {
            value: "131183",
            text: "长秋乡"
        }]
    }, {
        value: "131100",
        text: "新津县",
        children: [{
            value: "131102",
            text: "五津街道"
        }, {
            value: "131121",
            text: "花桥镇"
        }, {
            value: "131122",
            text: "花源镇"
        }, {
            value: "131123",
            text: "金华镇"
        }, {
            value: "131124",
            text: "普兴镇"
        }, {
            value: "131125",
            text: "兴义镇"
        }, {
            value: "131126",
            text: "新平镇"
        }, {
            value: "131127",
            text: "方兴镇"
        }, {
            value: "131128",
            text: "安西镇"
        }, {
            value: "131181",
            text: "永商镇"
        }, {
            value: "131182",
            text: "邓双镇"
        }, {
            value: "131183",
            text: "文井乡"
        }]
    }, {
        value: "131100",
        text: "都江堰市",
        children: [{
            value: "131102",
            text: "奎光塔街道"
        }, {
            value: "131121",
            text: "幸福街道"
        }, {
            value: "131122",
            text: "永丰街道"
        }, {
            value: "131123",
            text: "灌口街道"
        }, {
            value: "131124",
            text: "银杏街道"
        }, {
            value: "131125",
            text: "蒲阳镇"
        }, {
            value: "131126",
            text: "聚源镇"
        }, {
            value: "131127",
            text: "崇义镇"
        }, {
            value: "131128",
            text: "天马镇"
        }, {
            value: "131181",
            text: "石羊镇"
        }, {
            value: "131182",
            text: "柳街镇"
        }, {
            value: "131183",
            text: "玉堂镇"
        }, {
            value: "131183",
            text: "中兴镇"
        }, {
            value: "131183",
            text: "青城山镇"
        }, {
            value: "131183",
            text: "龙池镇"
        }, {
            value: "131183",
            text: "胥家镇"
        }, {
            value: "131183",
            text: "安龙镇"
        }, {
            value: "131183",
            text: "大观镇"
        }, {
            value: "131183",
            text: "向峨乡"
        }]
    }, {
        value: "131100",
        text: "彭州市",
        children: [{
            value: "131102",
            text: "天彭街道"
        }, {
            value: "131121",
            text: "龙门山镇"
        }, {
            value: "131122",
            text: "新兴镇"
        }, {
            value: "131123",
            text: "丽春镇"
        }, {
            value: "131124",
            text: "九尺镇"
        }, {
            value: "131125",
            text: "蒙阳镇"
        }, {
            value: "131126",
            text: "通济镇"
        }, {
            value: "131127",
            text: "丹景山镇"
        }, {
            value: "131128",
            text: "隆丰镇"
        }, {
            value: "131181",
            text: "敖平镇"
        }, {
            value: "131182",
            text: "磁峰镇"
        }, {
            value: "131183",
            text: "桂花镇"
        }, {
            value: "131183",
            text: "军乐镇"
        }, {
            value: "131183",
            text: "三界镇"
        }, {
            value: "131183",
            text: "小渔洞镇"
        }, {
            value: "131183",
            text: "红岩镇"
        }, {
            value: "131183",
            text: "升平镇"
        }, {
            value: "131183",
            text: "白鹿镇"
        }, {
            value: "131183",
            text: "葛仙山镇"
        }, {
            value: "131183",
            text: "致和镇"
        }]
    }, {
        value: "131100",
        text: "邛崃市",
        children: [{
            value: "131102",
            text: "文君街道"
        }, {
            value: "131121",
            text: "临邛街道"
        }, {
            value: "131122",
            text: "羊安镇"
        }, {
            value: "131123",
            text: "牟礼镇"
        }, {
            value: "131124",
            text: "桑园镇"
        }, {
            value: "131125",
            text: "平乐镇"
        }, {
            value: "131126",
            text: "夹关镇"
        }, {
            value: "131127",
            text: "火井镇"
        }, {
            value: "131128",
            text: "水口镇"
        }, {
            value: "131181",
            text: "固驿镇"
        }, {
            value: "131182",
            text: "冉义镇"
        }, {
            value: "131183",
            text: "回龙镇"
        }]
    }, {
        value: "131100",
        text: "崇州市",
        children: [{
            value: "131102",
            text: "崇阳街道"
        }, {
            value: "131121",
            text: "三江镇"
        }, {
            value: "131122",
            text: "江源镇"
        }, {
            value: "131123",
            text: "羊马镇"
        }, {
            value: "131124",
            text: "廖家镇"
        }, {
            value: "131125",
            text: "元通镇"
        }, {
            value: "131126",
            text: "观胜镇"
        }, {
            value: "131127",
            text: "怀远镇"
        }, {
            value: "131128",
            text: "三郎镇"
        }, {
            value: "131181",
            text: "街子镇"
        }, {
            value: "131182",
            text: "文井江镇"
        }, {
            value: "131183",
            text: "王场镇"
        }]
    }, {
        value: "131100",
        text: "简阳市",
        children: [{
            value: "131102",
            text: "简城街道"
        }, {
            value: "131121",
            text: "射洪坝街道"
        }, {
            value: "131122",
            text: "十里坝街道"
        }, {
            value: "131123",
            text: "杨柳街道"
        }, {
            value: "131124",
            text: "石桥镇"
        }, {
            value: "131125",
            text: "新市镇"
        }, {
            value: "131126",
            text: "石盘镇"
        }, {
            value: "131127",
            text: "东溪镇"
        }, {
            value: "131128",
            text: "平泉镇"
        }, {
            value: "131181",
            text: "禾丰镇"
        }, {
            value: "131182",
            text: "云龙镇"
        }, {
            value: "131183",
            text: "三星镇"
        }]
    }]
}
]